-- Reset catalog from 品名.xls (Sheet2)
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM order_items;
DELETE FROM dispatch_logs;
DELETE FROM payments;
DELETE FROM purchase_payments;
DELETE FROM orders;
DELETE FROM product_prices;
DELETE FROM products;
DELETE FROM product_categories;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO product_categories (merchant_id, parent_id, name, sort_order, status) VALUES
(1, NULL, '菇菌类', 1, 1),
(1, NULL, '花草香料类', 2, 1),
(1, NULL, '蔬果类', 3, 1);

-- 菇菌类: 21 products
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜草菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜冬菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜茶树菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '秀珍菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '平菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鸡腿菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '海鲜菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '杏鲍菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '白玉菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '蟹味菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '金针菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '白蘑菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '灵芝菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '真姬菇', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鹿茸菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '姬松菌', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '黑皮鸡枞菌', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '滑子菇', '桶', '桶', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '猴头菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '牛肝菌', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '猪肚菇', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '菇菌类' AND parent_id IS NULL LIMIT 1;
-- 花草香料类: 54 products
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '康乃馨', '扎', '扎', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '芝麻菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '玫瑰', '扎', '扎', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '薄荷叶尖', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '三色瑾', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '宝塔菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '石竹梅', '支', '支', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '绿线叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '情人草', '扎', '扎', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '番西', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '千叶吊兰', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜香茅', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '钢钱草', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '金不换', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '睡莲花瓣', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '薄荷叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '巴西叶', '支', '支', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '百里香', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '茅根', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '迷迭香', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '绿绣球', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '青紫苏', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜竹叶', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '泰国芫西', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '叼草', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '罗勒叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '冰草', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '芥末苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '兰花（罗兰花）', '扎', '扎', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜花椒', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '柠檬叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '大叶', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '酸膜叶', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '食用花', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '香椿苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '火箭苗', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '网纹叶', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '纤宝苗', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '茴香头', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '辣椒丝', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '马尾松针', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '落地球', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '斑斓叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '火红苗', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '五星花', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '碗豆苗', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '粽叶', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红南天竹叶', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '绿南天竹叶', '盒', '盒', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '剑叶', '支', '支', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红枫叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '尤加利', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '欧芹', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '欧芹叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '花草香料类' AND parent_id IS NULL LIMIT 1;
-- 蔬果类: 61 products
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '水果青瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '皇帝菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '日本青瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '西兰花苔', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '青瓜花', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红圆椒', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红叶生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '黄圆椒', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '罗马生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '五彩椒', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '狗芽生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜人参', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '黄狗生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '白果肉', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '绿珊瑚生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '小青桔', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '西生菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '圣女果', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红菊苣', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '黄圣女果', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '芦笋', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '串圣女果', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '红头菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '冰茄', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '羽甘兰', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '黄柠檬', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '紫甘蓝苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '青柠檬', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '紫白菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '豆苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '紫椰菜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '栗子南瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '紫包甘蓝', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '贵妃南瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '萝卜苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '贝贝南瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '雪里红', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '青瓜小南瓜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '樱桃萝卜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '太阳瓜', '只', '只', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '手指萝卜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '竹笋', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '心里美萝卜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '农家清水竹笋', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '青萝卜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜绍实', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '紫萝卜', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '花生芽250g', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '有壳板栗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜桑叶', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '栗子肉', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜核桃仁', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '玉米苗', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '包装海带苗', '包', '包', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜百合', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '藕带', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '金德百合', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '魔芋丝', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '秋葵', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '鲜莲子', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;
INSERT INTO products (merchant_id, category_id, name, unit, sale_units, sale_status) SELECT 1, id, '甜笋', '斤', '斤', 'ON' FROM product_categories WHERE merchant_id = 1 AND name = '蔬果类' AND parent_id IS NULL LIMIT 1;