spring:
  config:
    import: optional:classpath:application-dev-local.yml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vwholesale?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: vwholesale
    password: vwholesale
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.vwholesale: debug
